name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/aws-prueba
          APP_FILE: app.py
          ENVIRONMENT: production
      
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del proyecto
              cd aws-prueba && ls &&

              # Activar el entorno virtual
              source env/bin/activate &&

              # Actualizar el código desde la rama dev
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&

              # Instalar dependencias necesarias
              pip install -r requirements.txt &&

              # Detener cualquier proceso que esté usando el puerto 5000
              sudo fuser -k 5000/tcp &&

              # Ejecutar la aplicación Flask
              gunicorn -b 0.0.0.0:5000 app:app --daemon

              # Desactivar el entorno virtual
             
              '
